[2022-02-03 18:19:28,809] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [queued]>
[2022-02-03 18:19:28,823] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [queued]>
[2022-02-03 18:19:28,823] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:19:28,823] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-03 18:19:28,823] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:19:28,841] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-12-02 00:00:00+00:00
[2022-02-03 18:19:28,848] {standard_task_runner.py:52} INFO - Started process 1298 to run task
[2022-02-03 18:19:28,851] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-12-02T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpx4014e8k', '--error-file', '/tmp/tmpi3qfxdnv']
[2022-02-03 18:19:28,852] {standard_task_runner.py:77} INFO - Job 192: Subtask download_dataset_task
[2022-02-03 18:19:28,923] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [running]> on host bd2f56b76e32
[2022-02-03 18:19:28,970] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 18:19:28,990] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-12-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-02T00:00:00+00:00
[2022-02-03 18:19:28,991] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-03 18:19:28,991] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-12.csv > /opt/***/output_2019-12.csv']
[2022-02-03 18:19:29,004] {subprocess.py:85} INFO - Output:
[2022-02-03 18:19:44,029] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-03 18:19:44,066] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20191202T000000, start_date=20220203T181928, end_date=20220203T181944
[2022-02-03 18:19:44,090] {local_task_job.py:212} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-02-03 18:19:44,092] {process_utils.py:124} INFO - Sending Signals.SIGTERM to group 1298. PIDs of all processes in the group: [1298]
[2022-02-03 18:19:44,092] {process_utils.py:75} INFO - Sending the signal Signals.SIGTERM to group 1298
[2022-02-03 18:19:44,095] {process_utils.py:70} INFO - Process psutil.Process(pid=1298, status='terminated', exitcode=0, started='18:19:28') (1298) terminated with exit code 0
[2022-02-19 23:59:47,097] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [queued]>
[2022-02-19 23:59:47,117] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [queued]>
[2022-02-19 23:59:47,117] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:59:47,118] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 23:59:47,118] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:59:47,153] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-12-02 00:00:00+00:00
[2022-02-19 23:59:47,181] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-12-02T00:00:00+00:00', '--job-id', '304', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpqlts2e_z', '--error-file', '/tmp/tmpnvetz3yy']
[2022-02-19 23:59:47,201] {standard_task_runner.py:77} INFO - Job 304: Subtask download_dataset_task
[2022-02-19 23:59:47,170] {standard_task_runner.py:52} INFO - Started process 256 to run task
[2022-02-19 23:59:47,537] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [running]> on host da07aa254901
[2022-02-19 23:59:47,748] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-19 23:59:47,841] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-12-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-02T00:00:00+00:00
[2022-02-19 23:59:47,843] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 23:59:47,848] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-12.csv > /opt/***/output_2019-12.csv']
[2022-02-19 23:59:47,931] {subprocess.py:85} INFO - Output:
[2022-02-20 00:00:03,076] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-20 00:00:03,107] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20191202T000000, start_date=20220219T235947, end_date=20220220T000003
[2022-02-20 00:00:03,151] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-20 00:00:03,201] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:43:38,680] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [queued]>
[2022-02-23 20:43:38,700] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [queued]>
[2022-02-23 20:43:38,700] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:43:38,700] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 20:43:38,700] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:43:38,724] {taskinstance.py:1259} INFO - Executing <Task(BashOperator): download_dataset_task> on 2019-12-02 00:00:00+00:00
[2022-02-23 20:43:38,772] {standard_task_runner.py:52} INFO - Started process 525 to run task
[2022-02-23 20:43:38,803] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'download_dataset_task', 'scheduled__2019-12-02T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpa130isd5', '--error-file', '/tmp/tmpdge_p0m2']
[2022-02-23 20:43:38,807] {standard_task_runner.py:77} INFO - Job 41: Subtask download_dataset_task
[2022-02-23 20:43:38,945] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.download_dataset_task scheduled__2019-12-02T00:00:00+00:00 [running]> on host 1c172e0325c8
[2022-02-23 20:43:39,112] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:43:39,179] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2019-12-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-12-02T00:00:00+00:00
[2022-02-23 20:43:39,188] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-02-23 20:43:39,189] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'curl -sS https://nyc-tlc.s3.amazonaws.com/trip+data/fhv_tripdata_2019-12.csv > /opt/***/output_2019-12.csv']
[2022-02-23 20:43:39,273] {subprocess.py:85} INFO - Output:
[2022-02-23 20:43:54,725] {subprocess.py:93} INFO - Command exited with return code 0
[2022-02-23 20:43:54,789] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=download_dataset_task, execution_date=20191202T000000, start_date=20220223T204338, end_date=20220223T204354
[2022-02-23 20:43:54,850] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 20:43:55,090] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
