[2022-02-03 18:17:35,987] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-03 18:17:36,010] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-03 18:17:36,010] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:17:36,011] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-03 18:17:36,011] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:17:36,033] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 00:00:00+00:00
[2022-02-03 18:17:36,040] {standard_task_runner.py:52} INFO - Started process 1088 to run task
[2022-02-03 18:17:36,044] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-01-02T00:00:00+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmp7xpnd1cg', '--error-file', '/tmp/tmpx37dnord']
[2022-02-03 18:17:36,046] {standard_task_runner.py:77} INFO - Job 168: Subtask local_to_gcs_task
[2022-02-03 18:17:36,138] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [running]> on host bd2f56b76e32
[2022-02-03 18:17:36,277] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 18:17:36,314] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T00:00:00+00:00
[2022-02-03 18:18:04,048] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 18:18:04,063] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=local_to_gcs_task, execution_date=20190102T000000, start_date=20220203T181735, end_date=20220203T181804
[2022-02-03 18:18:04,117] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 18:18:04,155] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
<<<<<<< HEAD
[2022-02-23 21:00:10,043] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-23 21:00:10,058] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [queued]>
[2022-02-23 21:00:10,058] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:00:10,058] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 21:00:10,059] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 21:00:10,074] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-01-02 00:00:00+00:00
[2022-02-23 21:00:10,081] {standard_task_runner.py:52} INFO - Started process 1253 to run task
[2022-02-23 21:00:10,084] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-01-02T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpz3f_kzsi', '--error-file', '/tmp/tmp1kj50t9l']
[2022-02-23 21:00:10,085] {standard_task_runner.py:77} INFO - Job 53: Subtask local_to_gcs_task
[2022-02-23 21:00:10,143] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-01-02T00:00:00+00:00 [running]> on host 1c172e0325c8
[2022-02-23 21:00:10,188] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 21:00:10,220] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-01-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-01-02T00:00:00+00:00
[2022-02-23 21:00:41,744] {python.py:175} INFO - Done. Returned value was: None
[2022-02-23 21:00:41,755] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=local_to_gcs_task, execution_date=20190102T000000, start_date=20220223T210010, end_date=20220223T210041
[2022-02-23 21:00:41,783] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 21:00:41,815] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
=======
>>>>>>> origin/master
