[2022-02-03 18:18:39,189] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [queued]>
[2022-02-03 18:18:39,203] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [queued]>
[2022-02-03 18:18:39,203] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:18:39,203] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-03 18:18:39,203] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-03 18:18:39,218] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-09-02 00:00:00+00:00
[2022-02-03 18:18:39,224] {standard_task_runner.py:52} INFO - Started process 1212 to run task
[2022-02-03 18:18:39,227] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-09-02T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpab3n4vc_', '--error-file', '/tmp/tmpdh9d116y']
[2022-02-03 18:18:39,228] {standard_task_runner.py:77} INFO - Job 182: Subtask local_to_gcs_task
[2022-02-03 18:18:39,296] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [running]> on host bd2f56b76e32
[2022-02-03 18:18:39,357] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-03 18:18:39,381] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T00:00:00+00:00
[2022-02-03 18:18:40,912] {python.py:175} INFO - Done. Returned value was: None
[2022-02-03 18:18:40,939] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=local_to_gcs_task, execution_date=20190902T000000, start_date=20220203T181839, end_date=20220203T181840
[2022-02-03 18:18:41,038] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-03 18:18:41,142] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-19 23:58:18,677] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [queued]>
[2022-02-19 23:58:18,693] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [queued]>
[2022-02-19 23:58:18,693] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:58:18,693] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-19 23:58:18,693] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 23:58:18,714] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-09-02 00:00:00+00:00
[2022-02-19 23:58:18,720] {standard_task_runner.py:52} INFO - Started process 138 to run task
[2022-02-19 23:58:18,724] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-09-02T00:00:00+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmpiqs1oyoq', '--error-file', '/tmp/tmpyu3x68rt']
[2022-02-19 23:58:18,725] {standard_task_runner.py:77} INFO - Job 291: Subtask local_to_gcs_task
[2022-02-19 23:58:18,846] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [running]> on host da07aa254901
[2022-02-19 23:58:18,895] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-19 23:58:18,926] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T00:00:00+00:00
[2022-02-19 23:58:20,414] {python.py:175} INFO - Done. Returned value was: None
[2022-02-19 23:58:20,570] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=local_to_gcs_task, execution_date=20190902T000000, start_date=20220219T235818, end_date=20220219T235820
[2022-02-19 23:58:20,626] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-19 23:58:20,668] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-23 20:42:58,877] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [queued]>
[2022-02-23 20:42:58,894] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [queued]>
[2022-02-23 20:42:58,895] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:42:58,895] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-02-23 20:42:58,895] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-02-23 20:42:58,913] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2019-09-02 00:00:00+00:00
[2022-02-23 20:42:58,922] {standard_task_runner.py:52} INFO - Started process 452 to run task
[2022-02-23 20:42:58,926] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'fhv_gcs_dag', 'local_to_gcs_task', 'scheduled__2019-09-02T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/fhv_gcs_dag.py', '--cfg-path', '/tmp/tmplolks4n5', '--error-file', '/tmp/tmpu9d12y2r']
[2022-02-23 20:42:58,927] {standard_task_runner.py:77} INFO - Job 31: Subtask local_to_gcs_task
[2022-02-23 20:42:58,994] {logging_mixin.py:109} INFO - Running <TaskInstance: fhv_gcs_dag.local_to_gcs_task scheduled__2019-09-02T00:00:00+00:00 [running]> on host 1c172e0325c8
[2022-02-23 20:42:59,048] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-02-23 20:42:59,070] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=fhv_gcs_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2019-09-02T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2019-09-02T00:00:00+00:00
[2022-02-23 20:43:01,372] {python.py:175} INFO - Done. Returned value was: None
[2022-02-23 20:43:01,385] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=fhv_gcs_dag, task_id=local_to_gcs_task, execution_date=20190902T000000, start_date=20220223T204258, end_date=20220223T204301
[2022-02-23 20:43:01,431] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-02-23 20:43:01,469] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
